### PR TITLE
Updated de_DE.json 

### PR DESCRIPTION
**Pull request by ken-der-guru**
Updated the German translation and corrected some grammar and spelling mistakes.

Also I noticed that https://github.com/harmonoid/translations/blob/d3660a2dad4a57fd8d89a70a4e71896b9941a0ad/translations/en_US.json#L72 and https://github.com/harmonoid/translations/blob/d3660a2dad4a57fd8d89a70a4e71896b9941a0ad/translations/en_US.json#L73 are the same, therefore I think one of them should get removed to avoid confusion.

### CODE REVIEW

**Comment by ken-der-guru** [comment]
I think that this duplicate is the reason the check failed.

**Comment by alexmercerind** [comment]
Yeah, it's duplicate. One has a period in it & another one doesn't.

According to Material Design specification, full stops should be omitted when sentence exists alone (mobile) & should be preserved when in combination with other sentences i.e. a paragraph. Let's have both since few languages have different punctuation & symbols etc.

<hr>

Thanks for the translation updates! I'm about to release v0.3.5 with few important things in a while.


> Some **necessary fixes important for project to receive quickly**. Most importantly:
> 
> - NAS / Samba file-system support for Windows has been fixed.
> - Thumbnail toolbar is no longer missing on Windows.
> - Some specific ROMs/devices will no longer face playback issues on Android.
> - Issue that caused opening music from File Explorer to make Harmonoid window restored on Windows has been fixed.
> - Harmonoid window no longer freezes when quitting on Windows 7 (backward-compatibility).
> 
> ## Highlights
> 
> - Fixed NAS / SMB support on Windows.
> - Fixed issue that caused opening file from File Explorer to make Harmonoid window restored (if already maximized) on Windows.
> - Added ability to disable all audio filters on Android (disabled by default). Some ROMs & devices are having trouble.
> - Disabled GTK header-bar on Gnome desktop environment.
> - Fixed unresponsive process when closing window on Windows 7 only.
> - Updated new page animation when clicking on hyperlinks.
> - Added support for installing for current users only on Windows (#372).
> - Fixed next/previous buttons not greyed out in `ModernNowPlayingScreen` (#369).
> - Made fallback album arts configurable (#379).
> - Fixed missing thumbnail toolbar buttons on Windows.
> - Fixed "CANCEL" button on minimum file size dialog popping `Navigator` on the wrong `BuildContext`.
> - Migrated project to API changes in [`package:media_kit`](https://github.com/alexmercerind/media_kit).
> - Safer hyperlinks. Added null-check after lookup for album/artist in [`package:media_library`](https://github.com/alexmercerind/media_library) `HashSet`(s) (#366). 
> - Added multiple genre support (not exposed yet).
> - Added `Play all` button next to `Shuffle` on Albums & Artists screens to play them orderly.
> - Now background visuals are stored as animated WebP.
>   This has significantly reduced bundle size & [also improved Linux's performance with `ModernNowPlayingScreen` (?)](https://github.com/sony/flutter-embedded-linux/issues/245#issuecomment-1005457516).

**Comment by alexmercerind** [comment]
I have few other requests too.
Can we shorten few labels, maybe change grammar slightly or whatever while still conveying message?

|German |English|Remark|
|---------|--------|--------|
|WhatsApp Image 2023-01-04 at 8 34 34 PM (1)|WhatsApp Image 2023-01-04 at 8 34 35 PM| The subtitle will appear better in single line.|
|WhatsApp Image 2023-01-04 at 8 34 35 PM (1)|WhatsApp Image 2023-01-04 at 8 34 34 PM (2)| The label in search-bar is clipped. Something that can be done?|
|WhatsApp Image 2023-01-04 at 8 34 36 PM (1)|WhatsApp Image 2023-01-04 at 8 34 36 PM| Is the subtitle really conveying the message correctly?|

**Comment by ken-der-guru** [comment]
I can probably look at that tomorrow.

**Comment by ken-der-guru** [comment]
Fullfiled the requests you made, shoud be fine to merge.

One question though, in german there is a formal and non-formal way of adressing someone, currently I used the formal way because its mostly the way software adresses the user, but now I sometime think it sounds a bit wierd. It also would be shorter to use the non-formal way in most cases.
Let me hear your thoughts on that

**Comment by alexmercerind** [comment]
Sounds good to me! Thanks for the translations, feel free to edit them out as you like.

**Pull request merged**
