### PR TITLE
Update ja_JP.json

### PR DESCRIPTION
**Pull request by maboroshin**

### CODE REVIEW

**Comment by maisondasilva** [comment]
@alexmercerind some lines I saw that it was changed in the variable example line 34, 38. 48 and 50 can we accept?

**Comment by maboroshin** [comment]
@maisondasilva This changes the quotation marks to Japanese parentheses. If it has to do with an variable error, there is no problem reverting back to English quotation marks.

**Comment by maisondasilva** [comment]
> @maisondasilva This changes the quotation marks to Japanese parentheses. If it has to do with an variable error, there is no problem reverting back to English quotation marks.

Yes, I'll wait for @alexmercerind to check

**Review by alexmercerind — APPROVED** [review]
LGTM!

Changing quotes shouldn't break anything. Failing CI was due to recent changes at [harmonoid/translations@`master`](https://github.com/harmonoid/translations/tree/master), which seems to be resolved after merging upstream.

Thanks for updates!

**Pull request merged**
