### PR TITLE
Create ca_ES.json

### PR DESCRIPTION
**Pull request by aniol**
Catalan translation.

### CODE REVIEW

**Comment by alexmercerind** [comment]
Thanks for the translations, I think #52 is updated version of this. Right?

**Comment by maisondasilva** [comment]
> Thanks for the translations, I think #52 is updated version of this. Right?

Version 49 doesn't have the error that #52 has in the line, the above check failed

**Review by maisondasilva — COMMENTED** [review]
I made a correction on line 197 and made a new submission!

**Comment by alexmercerind** [comment]
Let's go ahead then. Ideally all these files should've been changed in the same branch to avoid failing checks.

Why is it still failing though?

**Comment by maisondasilva** [comment]
I will ask you to place a new order together, because this is giving error! @aniol

**Pull request closed without merging**
